# Project Paths ###############################################################

BLD_DIR := ../build

# User Definitions #############################################################

TARGET = helloworld-rtems

C_SRC  = helloworld-rtems.c

A_SRC	 = 

PREFIX = sparc-gaisler-rtems5

-include $(BLD_DIR)/leon3.mk 
