# Project Paths ###############################################################

BLD_DIR := ../build

# User Definitions #############################################################

TARGET = helloworld-bare

C_SRC  = helloworld-bare.c

A_SRC	 = 

PREFIX = sparc-gaisler-elf

-include $(BLD_DIR)/leon3.mk 
