# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {filemgmt 56-99}  -suppress 
set_msg_config  -id {Synth 8-6014}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.cache/wt [current_project]
set_property parent.project_path E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library grlib {
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/stdlib/config_types.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/stdlib/config.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/stdlib/version.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/stdlib/stdlib.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/amba/amba.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/amba/devices.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/amba/ahbctrl.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/amba/ahbmst.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/amba/apbctrl.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/amba/apbctrlx.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/sparc/sparc.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/modgen/leaves.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/grlib/modgen/multlib.vhd
}
read_vhdl -library techmap {
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/gencomp/gencomp.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/allclkgen.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/allddr.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/allmem.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/allmul.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/allpads.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/alltap.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/buffer_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/clkand.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/clkgen.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/clkgen_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/clkmux.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/clkpad.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/inferred/ddr_inferred.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/ddr_ireg.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/ddr_oreg.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/inferred/ddr_phy_inferred.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/ddr_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/ddr_phy_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/ddrphy.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/inferred/ddrphy_datapath.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/grfpw_net.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/gencomp/netcomp.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/grgates.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/grlfpw_net.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/inpad.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/iopad.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/iopad_ds.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/leon3_net.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/inferred/memory_inferred.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/memory_kintex7.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/memory_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/memrwcol.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/inferred/mul_inferred.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/outpad.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/outpad_ds.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/pads_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/regfile_3p.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/syncram.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/syncram64.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/syncram_2p.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/syncram_dp.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/syncrambw.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/syncreg.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/tap.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/unisim/tap_unisim.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/techbuf.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/techmap/maps/techmult.vhd
}
read_vhdl -library gaisler {
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddrpkg.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddrintpkg.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/misc/misc.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/jtag/libjtagcom.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/jtag/jtag.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/jtag/ahbjtag.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/uart/uart.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/uart/libdcom.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/uart/ahbuart.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/uart/apbuart.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/arith/arith.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3/leon3.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/libfpu.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmuconfig.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/libiu.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmuiface.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/libcache.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/cachemem.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/cmvalidbits.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/uart/dcom.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/uart/dcom_uart.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddr2buf.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddr2spa.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddr2spax.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddr2spax_ahb.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddr2spax_ddr.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/ddr/ddrphy_wrap.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/arith/div32.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/dsu3.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/dsu3x.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/net/net.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/misc/gptimer.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/libleon3.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/grfpwx.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/grfpwxsh.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/grlfpwx.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/irqmp/irqmp.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/iu3.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/jtag/jtagcom.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/jtag/jtagcom2.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/memctrl/memctrl.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/spi/spi.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/leon3s.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/leon3x.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/libmmu.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmu.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/mmu_acache.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/mmu_cache.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/mmu_dcache.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/mmu_icache.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmulru.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmulrue.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmutlb.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmutlbcam.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/srmmu/mmutw.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/arith/mul32.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/proc3.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/regfile_3p_l3.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/misc/rstgen.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/spi/spimctrl.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/tbufmem.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/grlib-gpl-2019.4-b4246/lib/gaisler/leon3v3/tbufmem_2p.vhd
}
read_vhdl -library xil_defaultlib {
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/project_leon3/config.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/project_leon3/led_apb.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/spi/spimctrl.vhd
  E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/sources_1/imports/project_leon3/nexys4_top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/constrs_1/imports/leon3-digilent-nexys4ddr/leon3mp.xdc
set_property used_in_implementation false [get_files E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/constrs_1/imports/leon3-digilent-nexys4ddr/leon3mp.xdc]

read_xdc E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/constrs_1/imports/project_leon3/nexys4_top.xdc
set_property used_in_implementation false [get_files E:/525.612/Needles_LEON3/Needles_LEON3/Needles_LEON3.srcs/constrs_1/imports/project_leon3/nexys4_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top nexys4_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nexys4_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nexys4_top_utilization_synth.rpt -pb nexys4_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
